### ISSUE TITLE
Slider Widget funktioniert nicht in Vis2

### ISSUE THREAD

**Issue by peoples0815** [ioBroker/ioBroker.vis-metro#24]
**Describe the bug**  
Beispielsweise das Slider Widget wird zwar im Editor angezeigt aber nicht in Vis.

In der Developer-Console wird folgender Fehler ausgegeben:
`visCanWidget.jsx:1325 can't render tplMetroSliderVertical w000048 on "default": 
renderWidget @ visCanWidget.jsx:1325
visCanWidget.jsx:1329 0 - TypeError: $this.metroSlider is not a functionTypeError: $this.metroSlider is not a function
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 1 -     at Object.slider (<anonymous>:261:19)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 2 -     at Object.eval (tplMetroSliderVertical.js:70:77)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 3 -     at Function.<anonymous> (http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:1728:17)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 4 -     at a.each (http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 5 -     at http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:1727:17
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 6 -     at HTMLDivElement.<anonymous> (http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:1419:98)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 7 -     at a.each (http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:343:211)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 8 -     at Function.hookup (http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:1418:19)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 9 -     at Function.frag (http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:1405:22)
renderWidget @ visCanWidget.jsx:1329
visCanWidget.jsx:1329 10 -     at r (http://192.168.3.3:8082/vis-2/lib/js/can.custom.js:1370:22)
renderWidget @ visCanWidget.jsx:1329`

**Comment by peoples0815** [comment]
Ich habe den Vis2 Adapter nochmals gelöscht und neu installiert, nun funktioniert es
